version: "3.7"
services: 
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports: 
      - "1025:1025"
      - "8025:8025"
    restart: "unless-stopped"
    container_name: "mailhog"
    hostname: "mailhog"
