version: "3.7"
services: 
  postgis:
    image: kartoza/postgis:15-3
    container_name: postgis
    environment: 
      POSTGRES_USER: "docker"
      POSTGRES_PASS: "docker"
    ports: 
      - "25432:5432"
  pgadmin4:
    image: dpage/pgadmin4:2023-04-04-1
    container_name: postgis-admin
    environment: 
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "8080:80"
    links: 
      - "postgis"
