version: "3.8"

services:
  registry:
    image: registry:2
    restart: unless-stopped
    container_name: registry
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./data:/var/lib/registry
