apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgis-dpl
  name: postgis-dpl
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgis-dpl
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: root
        - name: PGADMIN_DEFAULT_PASSWORD
          value: 123@abc..
        image: kartoza/postgis
        name: postgisdb
        ports:
        - containerPort: 5432
      restartPolicy: Always