version: "3.7"
services: 
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: "1234"
    ports: 
      - "3306:3306"
  postgis:
    image: kartoza/postgis
    environment: 
      POSTGRES_USER: "docker"
      POSTGRES_PASS: "docker"
    ports: 
      - "25432:5432"
